development:
  adapter: postgresql
  encoding: utf8
  database: stacksocial_development
#  username: name
#  password: my_db_password
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: stacksocial_test
#  username: name
#  password: my_db_password
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  database: stacksocial_production
#  username: name
#  password: my_db_password
  host: localhost