development:
  adapter: postgresql
  encoding: utf8
  database: stacksocial_development
#  username: name
#  password: my_db_password
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: stacksocial_test
#  username: name
#  password: my_db_password
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  database: dc7ogsb28bhs4a
  username: ahibjjzpoubhyz
  password: Ipgx2hDGCNzgSrLDE4RuCmnmiu
  host: ec2-54-235-152-226.compute-1.amazonaws.com